repos:

- repo: https://github.com/econchick/interrogate
  rev: 1.2.0
  hooks:
    - id: interrogate
      exclude: ^(docs|setup.py|tests)
      args: [--config=pyproject.toml]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.1.0
  hooks:
    - id: trailing-whitespace
      exclude: tests/data
    - id: check-ast
    - id: debug-statements
    - id: end-of-file-fixer
    - id: check-docstring-first
    # - id: check-added-large-files
    - id: requirements-txt-fixer
    - id: file-contents-sorter
      files: requirements-dev.txt

- repo: https://github.com/pycqa/flake8
  rev: 3.7.9
  hooks:
    - id: flake8
      exclude: docs/source/conf.py
      args: [--max-line-length=105, --ignore=E203,E501,W503, --select=select=C,E,F,W,B,B950]

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort (python)
      args: ["--profile", "black", "--filter-files", "--lines-after-imports=2", "--project=gcm_filters", "--multi-line=3", "--lines-between-types=1", "--trailing-comma", "--force-grid-wrap=0", "--use-parentheses", "--line-width=88"]

- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
    language_version: python3

# - repo: https://github.com/pre-commit/mirrors-mypy
#   rev: v0.982
#   hooks:
#   - id: mypy
#     additional_dependencies: [types-setuptools, types-PyYAML]
#     exclude: docs/source/conf.py
#     args: [--ignore-missing-imports]

# too annoying with notebooks
# - repo: https://github.com/codespell-project/codespell
#   rev: v1.16.0
#   hooks:
#     - id: codespell
#       args:
#         - --quiet-level=2
