version: 2

# Build PDF only
formats:
  - pdf

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"

# uncomment to build from this exact version of package
# the downside is the version listed in the docs will be a dev version
# if uncommenting this, comment out installing pypi version of package in docs/env file
# python:
#   install:
#     - method: pip
#       path: ./

conda:
    environment: docs/environment.yml

sphinx:
  configuration: docs/conf.py
  # fail_on_warning: true
