name: test-env-extract-model
channels:
  - conda-forge
dependencies:
  - python=3.11
  - cf_xarray
  - dask
  - netcdf4
  - numpy
  - pip
  - requests
  - scikit-learn
  - xarray
  # - xoak
  - pytest
  - pytest-benchmark
  - pip:
    - xroms >=0.6.2
    - codecov
    - pytest-cov
    - coverage[toml]
    # - git+https://github.com/kthyng/xoak@include_distances
