name: test-env
channels:
  - conda-forge
dependencies:
  - python=3.7
  - cartopy
  - cf_xarray
  - cmocean
  - dask
  - matplotlib
  - netcdf4
  - numpy
  - pip
  - pyinterp
  - requests
  - xarray
  - xcmocean
  - xesmf
  - pytest
  - pip:
    - codecov
    - pytest-cov
    - coverage[toml]
