name: test-env-mac-unix
channels:
  - conda-forge
dependencies:
  - python=3.9
  - cf_xarray>=0.6
  - dask <=2022.05.0 # for xESMF, https://github.com/axiom-data-science/extract_model/issues/49
  - netcdf4
  - numpy
  - pip
  - requests
  - scikit-learn  # used by xoak for tree
  - xarray
  - xesmf
  # - xoak
  - pytest
  - pytest-benchmark
  - pip:
    - codecov
    - pytest-cov
    - coverage[toml]
    - git+https://github.com/kthyng/xoak@include_distances
